export const GET_QUESTIONS_START = 'questions/GET_QUESTIONS_START';
export const GET_QUESTIONS_SUCCESS = 'questions/GET_QUESTIONS_SUCCESS';
export const GET_QUESTIONS_ERROR = 'questions/GET_QUESTIONS_ERROR';

export const GET_QUESTIONS_MORE_START = 'questions/GET_QUESTIONS_MORE_START';
export const GET_QUESTIONS_MORE_SUCCESS = 'questions/GET_QUESTIONS_MORE_SUCCESS';
export const GET_QUESTIONS_MORE_ERROR = 'questions/GET_QUESTIONS_MORE_ERROR';

export const QUESTION_LIST_HAS_NO_MORE = 'questions/QUESTION_LIST_HAS_NO_MORE';

