export const GET_ANSWERS_BY_QUESTION_ID_START = 'answers/GET_ANSWERS_BY_QUESTION_ID_START';
export const GET_ANSWERS_BY_QUESTION_ID_SUCCESS = 'answers/GET_ANSWERS_BY_QUESTION_ID_SUCCESS';
export const GET_ANSWERS_BY_QUESTION_ID_ERROR = 'answers/GET_ANSWERS_BY_QUESTION_ID_ERROR';

export const GET_ANSWERS_BY_QUESTION_ID_MORE_START = 'answers/GET_ANSWERS_BY_QUESTION_ID_MORE_START';
export const GET_ANSWERS_BY_QUESTION_ID_MORE_SUCCESS = 'answers/GET_ANSWERS_BY_QUESTION_ID_MORE_SUCCESS';
export const GET_ANSWERS_BY_QUESTION_ID_MORE_ERROR = 'answers/GET_ANSWERS_BY_QUESTION_ID_MORE_ERROR';

